name: Package

on:
  push:
    branches:
      - main
    paths:
      - 'XoniumTemplate.nuspec'

jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.X

      - name: Install NuGet CLI (Linux)
        run: |
          curl -sSL https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
          sudo apt-get install -y mono-complete

      - name: Create the package
        run: mono nuget.exe pack XoniumTemplate.nuspec -NoDefaultExcludes

      - name: Publish the package
        run: dotnet nuget push *.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
